In [2]:
import pandas as pd


In [27]:
#raw_csv_data = pd.read_csv("data/Absenteeism-data.csv", index_col="ID")
raw_csv_data = pd.read_csv("data/Absenteeism-data.csv")

raw_csv_data[:2]

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0

In [15]:
type(raw_csv_data)

pandas.core.frame.DataFrame

In [28]:
df = raw_csv_data.copy()

In [29]:
df[:5]

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [9]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [30]:
#display(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
ID                           700 non-null int64
Reason for Absence           700 non-null int64
Date                         700 non-null object
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB


In [31]:
df = df.drop(['ID'],axis=1)
df[:2]

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   

   Absenteeism Time in Hours  
0                          4  
1                          0

In [32]:
raw_csv_data[:2]

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0

In [33]:
# Reason for Absence -> categorical nominal variable
df['Reason for Absence'].min()

0

In [34]:
df['Reason for Absence'].max()

28

In [35]:
pd.unique(df['Reason for Absence'])

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [36]:
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [37]:
len(df['Reason for Absence'].unique())

28

In [40]:
sorted(df['Reason for Absence'].unique());

In [42]:
# Converting the categorical variable
reason_columns = pd.get_dummies(df['Reason for Absence'])
reason_columns['check'] = reason_columns.sum(axis=1)
reason_columns[:5]

0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  21  \
0  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
1  1  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
2  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   
3  0  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0   0   0   0   0   
4  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   

   22  23  24  25  26  27  28  check  
0   0   0   0   0   1   0   0      1  
1   0   0   0   0   0   0   0      1  
2   0   1   0   0   0   0   0      1  
3   0   0   0   0   0   0   0      1  
4   0   1   0   0   0   0   0      1

In [43]:
reason_columns['check'].sum(axis=0)

700

In [44]:
reason_columns['check'].unique()

array([1], dtype=int64)

In [45]:
reason_columns = reason_columns.drop(['check'],axis=1)
reason_columns[:5]

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  \
0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
3   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

   19  21  22  23  24  25  26  27  28  
0   0   0   0   0   0   0   1   0   0  
1   0   0   0   0   0   0   0   0   0  
2   0   0   0   1   0   0   0   0   0  
3   0   0   0   0   0   0   0   0   0  
4   0   0   0   1   0   0   0   0   0

#### avoid potential multicollinearity issues

In [46]:
reason_columns = pd.get_dummies(df['Reason for Absence'],drop_first=True)
reason_columns[:4]

1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  \
0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
3   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   

   21  22  23  24  25  26  27  28  
0   0   0   0   0   0   1   0   0  
1   0   0   0   0   0   0   0   0  
2   0   0   1   0   0   0   0   0  
3   0   0   0   0   0   0   0   0

#### Group the `Reasons for Absence`:

In [47]:
df.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [48]:
reason_columns.columns.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 21, 22, 23, 24, 25, 26, 27, 28], dtype=int64)

In [49]:
df = df.drop(['Reason for Absence'], axis=1)

In [60]:
df = df.drop([0,1,2,3], axis=1)

In [61]:
df[:2]

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   

   Absenteeism Time in Hours  
0                          4  
1                          0

In [51]:
reason_columns.loc[:,1:14][:2]

1   2   3   4   5   6   7   8   9   10  11  12  13  14
0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
1   0   0   0   0   0   0   0   0   0   0   0   0   0   0

In [53]:
reason_columns.loc[:,1:14].max(axis=1);

In [54]:
reason_type_1 = reason_columns.loc[:,1:14].max(axis=1) # 1->14
reason_type_2 = reason_columns.loc[:,15:17].max(axis=1) # 15->17
reason_type_3 = reason_columns.loc[:,18:21].max(axis=1) # 18->21
reason_type_4 = reason_columns.loc[:,22:].max(axis=1) # 22 -> 28

In [55]:
len(reason_type_1),len(reason_type_2),len(reason_type_3),len(reason_type_4)

(700, 700, 700, 700)

#### Concatenate Column Values

In [62]:
df = pd.concat([df,reason_type_1,reason_type_2,reason_type_3,reason_type_4],axis=1)


In [63]:
df[:2]

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   

   Absenteeism Time in Hours  0  1  2  3  
0                          4  0  0  0  1  
1                          0  0  0  0  0

In [64]:
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [65]:
columns_name = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours','Reason_1', 'Reason_2', 'Reason_3','Reason_4']

In [67]:
df.columns = columns_name

In [68]:
df[:2]

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   

   Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  
0                          4         0         0         0         1  
1                          0         0         0         0         0

#### Reorder Columns

In [69]:
column_names_reordered = ['Reason_1', 'Reason_2', 'Reason_3','Reason_4','Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [70]:
df = df[column_names_reordered]

In [71]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

#### Create a Checkpoint
* create a copy of the current state of the `df` DataFrame

In [72]:
df_reason_mod = df.copy()

In [73]:
df_reason_mod[:3]

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2

#### preprocessing the `Date` feature

In [74]:
type(df_reason_mod['Date'])

pandas.core.series.Series

In [76]:
type(df_reason_mod['Date'][0])

str

`%d` = date , `%m`=month, `%Y`=year, `%H`=hour , `%M`= min, `%S`= sec

In [77]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'], format ='%d/%m/%Y')

In [79]:
type(df_reason_mod['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [81]:
df_reason_mod['Date'][0]

Timestamp('2015-07-07 00:00:00')

In [86]:
df_reason_mod['Date'][0].month

7

In [93]:
list_months = []
list_months

[]

In [94]:
df_reason_mod.shape

(700, 14)

In [95]:
for i in range(df_reason_mod.shape[0]):
    list_months.append(df_reason_mod['Date'][i].month)

In [98]:
list_months;

In [96]:
len(list_months)

700

In [99]:
df_reason_mod['Month Value'] = list_months

In [100]:
df_reason_mod[:3]

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  
0         2     1                          4            7  
1         1     0                          0            7  
2         0     0                          2            7

In [101]:
df_reason_mod['Month Value'].unique()

array([ 7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6], dtype=int64)

In [102]:
# Extracting the Day of the Week
df_reason_mod['Date'][699].weekday()

3

In [103]:
def date_to_weekday(date_value):
    return date_value.weekday()

In [104]:
df_reason_mod['Day of the Week'] = df_reason_mod['Date'].apply(date_to_weekday)

In [105]:
df_reason_mod[:3]

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2

In [108]:
df_reason_mod = df_reason_mod.drop(['Date'],axis=1)

In [109]:
df_reason_mod[:2]

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1

In [110]:
df_reason_mod.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Month Value',
       'Day of the Week'], dtype=object)

In [120]:
column_names = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Month Value','Day of the Week','Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [116]:
colu = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Month Value',
       'Day of the Week']

In [117]:
df_reason_mod.columns =colu

In [118]:
df_reason_mod[:2]

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1

In [121]:
df_reason_mod = df_reason_mod[column_names]

In [122]:
df_reason_mod[:2]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0

#### Checkpoint after `Date` preprocessing

In [123]:
df_reason_date_mod = df_reason_mod.copy()

In [124]:
type(df_reason_date_mod['Transportation Expense'][0])

numpy.int64

In [125]:
type(df_reason_date_mod['Distance to Work'][0])

numpy.int64

In [126]:
type(df_reason_date_mod['Daily Work Load Average'][0])

numpy.float64

#### 'Education','Children','Pets'

In [129]:
df_reason_date_mod['Education'].unique()

array([1, 3, 2, 4], dtype=int64)

In [130]:
df_reason_date_mod['Education'].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

In [131]:
# putting 2,3,4 seperate becomes irrelevant as 1 -> 583 counts
df_reason_date_mod['Education'] = df_reason_date_mod['Education'].map({1:0, 2:1, 3:1, 4:1})

In [132]:
df_reason_date_mod['Education'].unique()

array([0, 1], dtype=int64)

In [133]:
df_reason_date_mod['Education'].value_counts()

0    583
1    117
Name: Education, dtype: int64

#### Final Checkpoint

In [134]:
df_preprocessed = df_reason_date_mod.copy()
df_preprocessed.tail()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
695               22          1         2     0                          8  
696               24          0         1     2                          3  
697               25          1         0     0                          8  
698               25          1         0     0                          2  
699               25          0         1     1                          2

In [136]:
df_preprocessed.to_csv('data/df_preprocessed_absenteeism.csv',index=False)